services:
  - type: web
    name: timetable-web
    env: python
    branch: main
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn web.app:app --bind 0.0.0.0:$PORT
    envVars: []
    autoDeploy: true
